### ISSUE TITLE
Review Deep Compression for implementation potential regarding deep nets

### ISSUE THREAD

**Issue by nyghtowl** [eclipse/deeplearning4j#1519]
Review recent paper http://arxiv.org/pdf/1510.00149v5.pdf to determine how to leverage the compression techniques in order to improve memory and computation efficiencies for deep networks

Consider alternative approach in this paper: http://arxiv.org/pdf/1511.06606v5.pdf

**Comment by AlexDBlack** [comment]
Presentation by the author of that: https://www.youtube.com/watch?v=hfFkS_vHslI
Worth watching, gives a good overview.

**Comment by fac2003** [comment]
This is a nice paper and method. If you are interested in trying something like this, I would recommend the Java DSIUtils implementation of Huffman coding: http://dsiutils.di.unimi.it/docs/it/unimi/dsi/compression/HuffmanCodec.html
Huffman coding of the weights is done post-training, so a pure Java solution would work well. I would be surprised if you can find a more efficient one than provided by DSIUtils.

For clustering the weights, you could use the QTclustering algorithm instead of KNN. This would provide better control on the performance degradation, and no need to prespecify the number of clusters. My lab has developed a QTClustering implementation in Java (http://icb.med.cornell.edu/wiki/index.php/Clustering). I'd be happy to release the code with a compatible license if that's of interest.

**Comment by agibsonccc** [comment]
@fac2003 We'd love to integrate this as a pre processing step for models. Please do.

**Comment by AlexDBlack** [comment]
Problem is: actually implementing the *full* version of this means we can't use standard BLAS operations. So it's a huge undertaking to actually implement this.

**Comment by nyghtowl** [comment]
@fac2003 thanks for the recommendations. Implementing this is to be determined. Still as Adam said we'd be interested in the QTClustering implementation you are offering to share especially if we go down this path. Is there something you need from us to get that released?

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
