### ISSUE TITLE
Error in the word2vec tutorial

### ISSUE THREAD

**Issue by julianmaster** [eclipse/deeplearning4j#2229]
There is some error in the tutorial : [https://deeplearning4j.org/word2vec](https://deeplearning4j.org/word2vec)  
- [x] Need to change the `writeFullModel` method to writeWord2VecModel in 
- [x] Need to change the `loadFullModel` method to readWord2VecModel
- [ ] The method `usePca(false)` and `plotVocab(tsne)` explain in  [visualizing-the-model](https://deeplearning4j.org/word2vec#visualizing-the-model) doesn't exist
- [ ] No explanation in the tutorial why a UIServer is start : `UiServer server = UiServer.getInstance();` and how to use it

**Comment by wobu** [comment]
also maybe we could add this to the Troubleshooting FAQ:
i was using Word2Vec in a Hadoop / Spark environment. And due to that there was a commons-codec.jar in the classpath with a lower version than 1.8 (version used by dl4j)

The lower version 1.4 seems to be binary compatible but had a different implementation behaviour in Base64 class.

See: http://lukieb.blogspot.de/2013/06/base64encodetostring-adds-newline.html

This had the effect that the persistet Word2Vec Model was broken and couldn't be loaded anymore.

**Comment by raver119** [comment]
Oops. Thanks for letting me know. Fix incoming.

**Comment by tomthetrainer** [comment]
- [X ]  Need to change the writeFullModel method to writeWord2VecModel in
- [ X]  Need to change the loadFullModel method to readWord2VecModel
- [ ]  The method usePca(false) and plotVocab(tsne) explain in visualizing-the-model doesn't exist
- [ ]  No explanation in the tutorial why a UIServer is start : UiServer server = UiServer.getInstance(); and how to use it

First two done, last two require more that a quick edit.

**Comment by agibsonccc** [comment]
Closing old issues.
