### ISSUE TITLE
No way to use dl4j-ui visualization with early stopping

### ISSUE THREAD

**Issue by ghost** [eclipse/deeplearning4j#2841]
Early stopping lacks a hook to connect UI visualizations to it.

**Comment by agibsonccc** [comment]
@crockpotveggies I thought you did some stuff with this?

**Comment by crockpotveggies** [comment]
Yes, when Alex made changes to prepare for spark parallel it broke it
again. I can prioritize it and get it working again

**Comment by dykens** [comment]
Hi, was it fixed yet, if so, how can it be done?

**Comment by AlexDBlack** [comment]
I thought this should be possible already, unless I'm missing something?
Just define your net, add the UI (stats listener) as before, then pass the net (instead of just the configuration) it to the EarlyStoppingTrainer.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/earlystopping/trainer/EarlyStoppingTrainer.java#L46

**Comment by crockpotveggies** [comment]
Unfortunately it triggers errors in Early Stopping. It has to do with how
listeners are invoked. B/c models are replicated, not all of information is
being collected and StatsListener pukes when it tries to collect certain
parameter ratios.

**Comment by AlexDBlack** [comment]
@crockpotveggies that sounds like parallel early stopping trainer, not the normal/standard one?
Either way, they both need to be tested I guess...

**Comment by crockpotveggies** [comment]
Yes parallel early stopping. I'm going to look at it simultaneously while I
do benchmarks. Fix is probably simple. Or we can override the metrics
causing the issue

**Comment by raver119** [comment]
I guess this issue can be closed now as implemented?
