### ISSUE TITLE
Support Keras Masking layers

### ISSUE THREAD

**Issue by ghost** [eclipse/deeplearning4j#3979]
When trying to import this model from keras:

https://gist.github.com/catalano-federico/75be3795c7504e3aeb3178aa1b74230a

i obtain an error regarding the masking layer saying  that is not supported

**Comment by raver119** [comment]
Is this still viable issue?

**Comment by Anriod** [comment]
Will support be addded ? I'm using SNAPSHOTS and its able to convert the model but not read it again - 
`Caused by: java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.deeplearning4j.nn.conf.layers.util.MaskZeroLayer]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?) `

**Comment by AlexDBlack** [comment]
@Anriod that exception is not related to Keras import. It will very likely happen if you used the layer directly in DL4J (no import)
I've opened a separate issue for that here: https://github.com/deeplearning4j/deeplearning4j/issues/7409

**Comment by agibsonccc** [comment]
https://github.com/eclipse/deeplearning4j/issues/7409
