### ISSUE TITLE
where is the TL;DR?

### ISSUE THREAD

**Issue by codehustler** [eclipse/deeplearning4j#4363]
great project, but I think its missing a real minimal quickstart tutorial. 

The pom file, you think should be the one a project should use, is way to bloated for my taste and not a good example because there is so much stuff in there that has nothing to do with DL4J. Stuff like automated code formatting, maven version enforcing, lint... this stuff only distracts new users from the required setup.

What I would like to see is a simple demo project boiled down to the bare minimum, e.g.:
add this dependency to your POM
sample code for a NN to get started
run a training session
proof it worked

**Comment by raver119** [comment]
Here's site full of TL/DRs: https://deeplearning4j.org

**Comment by agibsonccc** [comment]
@Mulder8472 so to make this more productive. What exactly is wrong with: http://deeplearning4j.org/quickstart ? The [examples](http://github.com/deeplearning4j/dl4j-examples) are literally import -> run whatever you want. Give me a breakdown here. A lot of the things you're talking about are already present. You don't need to write any code.

**Comment by Mulder8472** [comment]
OK, as an experienced programmer, I usually look for a bare minimum example to get started. I don't need an explanation of the standard prerequisites, such as maven or any IDE. When I look at https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/pom.xml

there are several things in there that, IMHO, don't qualify for a basic example, such as:
* parent-child project, should be standallone
* distribution management, why that in an example? someone who is downloading this does not run "mvn deploy" i guess
* while its nice to have a big example including jfreechart and logging and such, it diverts the attention away from the real purpose of a bare minimum example which I am looking for. So I would like to see just that.
* I cannot just copy the required dependencies from that pom file because the versions are declared in the parent pom
* the plugins in the that pom look obsolete (again, distracts from the important stuff)


@raver119 the link you posted is the exact opposite of TL;DR ;) thats fine, I like the documentation, don't get me wrong.

**Comment by Mulder8472** [comment]
this is good!: https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/basic/BasicRNNExample.java

had to dig deep to find it, often, projects put each example in a standallone project, that helps with keeping things separated. I.e. this example does not require jfreechart. In fact, in order to get this going in a brand new project, my pom is only 25 lines of xml:


```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>codehustler</groupId>
	<artifactId>dl4j-quickstart</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>		
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native</artifactId>
			<version>0.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>0.9.1</version>
		</dependency>
	</dependencies>
</project>
```

**Comment by tomthetrainer** [comment]
Are you looking for us  to provide something like this..

https://github.com/treo/dl4j-minimal-example

Basically a FeedForward Neural Network , CSV data, Iris, similar to ones we have and nothing else. 

No UI no spark, just the basics.

**Comment by RobAltena** [comment]
I disagree with "every example should be stand alone". It is not ok to have `N examples` copies of the same pom.xml. in a repository.  There is [documentation](https://deeplearning4j.org/documentation) and [tutorials](https://deeplearning4j.org/tutorials).

**Comment by saudet** [comment]
@Mulder8472 That's 25 lines we could put in quickstart.md under the "Using DL4J In Your Own Projects: Configuring the POM.xml File" section for people to copy/paste. in any case, please send a pull request where you believe we should have that documented. Thanks!
