### ISSUE TITLE
DL4J/DataVec licensing issues

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5878]
Moved from comment: https://github.com/deeplearning4j/deeplearning4j/pull/5873#issuecomment-404030494

**DataVec**:  Some things which I wasn't aware of until now, but look suspicious:

Some content in ```org.datavec.api.io.*```
After googling the comments, looks like these might have come from Hadoop originally from Canova (which later became Datavec)

https://github.com/deeplearning4j/deeplearning4j/blob/6e26529143d51934d7a3fa24cb2af0b1436b1544/datavec/datavec-api/src/main/java/org/datavec/api/io/RawComparator.java
https://hadoop.apache.org/docs/r1.0.4/api/org/apache/hadoop/io/RawComparator.html

https://github.com/deeplearning4j/deeplearning4j/blob/6e26529143d51934d7a3fa24cb2af0b1436b1544/datavec/datavec-api/src/main/java/org/datavec/api/io/DataInputBuffer.java
https://hadoop.apache.org/docs/r1.0.4/api/index.html?org/apache/hadoop/io/DataInputBuffer.html

Same with: https://github.com/deeplearning4j/deeplearning4j/tree/6e26529143d51934d7a3fa24cb2af0b1436b1544/datavec/datavec-api/src/main/java/org/datavec/api/io/serializers

And some of (Buffer and Index at least, not sure about the others. Record and SequenceRecord are ours though):
https://github.com/deeplearning4j/deeplearning4j/tree/6e26529143d51934d7a3fa24cb2af0b1436b1544/datavec/datavec-api/src/main/java/org/datavec/api/records

Otherwise datavec looks OK

**DL4J**:

Everything under this package looks suspicious: https://github.com/deeplearning4j/deeplearning4j/tree/43e1f321925db7b240f590d66990495b57af04b9/deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp-chinese/src/main/java/org/ansj
https://github.com/NLPchina/ansj_seg/tree/master/src/main/java/org/ansj

Aforementioned PR removed header from some of these, but others are incorrect. https://github.com/deeplearning4j/deeplearning4j/tree/43e1f321925db7b240f590d66990495b57af04b9/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-play/src/main/resources/deeplearning4jUiAssets/legacy
https://github.com/deeplearning4j/deeplearning4j/blob/43e1f321925db7b240f590d66990495b57af04b9/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-play/src/main/resources/deeplearning4jUiAssets/legacy/js/nearestneighbors/node_modules/director/build/director.js
Another one that has incorrect copyright header is jquery.rest.min.js. That's by no means a complete list, just some examples. We'll need a more thorough pass here... there's a mix of our content, and 3rd party here.

Aha! Link: https://skymindai.aha.io/features/DL4J-85

**Comment by wangfeng-skymind** [comment]
yeah,the chinese text tokenizer algorithm is from:
https://github.com/NLPchina/ansj_seg

**Comment by saudet** [comment]
@sshepel We'll need to remove the header files from the classes in the `org.ansj` package.

**Comment by sshepel** [comment]
@saudet got it!

**Comment by sshepel** [comment]
@saudet I have remove CHs from ansj, but I'm not sure that we should remove it from `deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp-chinese/src/main/java/org/deeplearning4j/text/tokenization/tokenizer/ChineseTokenizer.java`, because this file was created by @wangfeng-skymind .
@wangfeng-skymind could you please confirm this...

And there are still some files that needs to be reviewed:
- [ ] deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp-japanese/src/main/java/com/atilika/kuromoji
- [ ] nd4j/nd4j-common/src/main/java/org/nd4j/util/FingerPrintKeyer.java
- [ ] libnd4j/include/ops/declarable/generic/parity_ops/space_to_batch.cpp
- [ ] libnd4j/include/ops/declarable/generic/parity_ops/strided_slice.cpp
- [ ] nd4j/nd4j-serde/nd4j-camel-routes/nd4j-kafka/src/main/test/java/org/nd4j/kafka/EmbeddedKafkaCluster.java
- [ ] nd4j/nd4j-serde/nd4j-camel-routes/nd4j-kafka/src/main/test/java/org/nd4j/kafka/EmbeddedZookeeper.java
- [ ] nd4j/nd4j-serde/nd4j-aeron/src/main/java/org/nd4j/aeron/util/LogInspector.java
- [ ] deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp-japanese

PR for these changes is https://github.com/deeplearning4j/deeplearning4j/pull/5979

**Comment by saudet** [comment]
`ChineseTokenizer.java` seems fine yes, it's "ours".
