### ISSUE TITLE
Downloader maintenance

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#6823]
While messing around with the new KMNIST dataset I stumbled on this [Downloader ](https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-common/src/main/java/org/nd4j/resources/Downloader.java)utility in ND4J.

There are a few things I would like to do:

1. Should we move this to datavec ? And if we do move it to datavec, where?
Plenty of pipelines will include a `DownloadAndExtract` step.

2. Add a method to download and extract without checking the checksum.

3. Start using the downloader class in the examples where we are using the old
    `FileUtils.copyURLToFile(new URL(filename), destFile);`  quite a bit.

Aha! Link: https://skymindai.aha.io/features/DL4J-42

**Comment by AlexDBlack** [comment]
> Should we move this to datavec ?

No, it's in nd4j-common which should be usable everywhere in DataVec (and DL4J etc) already - i.e., it is a transitive dependency. If not, feel free to add nd4j-common as a dependency anywhere it is required.

> Add a method to download and extract without checking the checksum

Hm... sure, though checking downloads is very important. I've wasted many hours in the past debugging issues due to corrupted MNIST data, before we properly implemented validation. Unless there's a very good reason not to validate, validation should always be done IMO.

> Start using the downloader class in the examples where we are using the old
FileUtils.copyURLToFile(new URL(filename), destFile); quite a bit.

Sounds good, I'm definitely in favor of cleaning up/standardizing this.

**Comment by RobAltena** [comment]
> Hm... sure, though checking downloads is very important. I've wasted many hours in the past debugging issues due to corrupted MNIST data, 

This makes me think we should validate the files every time we construct the iterator. We only check for the presence of the files to decide whether to download and check.

We should change to the time-out version of `copyURLToFile`, then for most use cases we can reasonably assume the file downloaded successfully if there are no exceptions.

**Comment by AlexDBlack** [comment]
> This makes me think we should validate the files every time we construct the iterator

It's probably a good idea to apply consistently everywhere.

We do it for zoo models for example every time:
https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/deeplearning4j/deeplearning4j-zoo/src/main/java/org/deeplearning4j/zoo/ZooModel.java#L84-L95
But it's not done everywhere.
