### ISSUE TITLE
ND4J: Native library AVX validation and logging (usability)

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7834]
Consider the following situations:

1. User has x86-64 binaries in their project/uber-jar, but their CPU supports avx2 or avx512
2. User has avx2 binaries, but their CPU doesn't support avx2
3. User has windows binaries, but they are trying to run it on linux

Currently, the behaviour is as follows, for each of these cases:
1. No warning or information that they could get better performance with AVX
2. Not 100% sure, but presumably a javacpp native library loading issue?
3. A NoAvailableBackendException

Usability for all 3 cases could be improved. We should log a useful warning (or throw an exception) with the following information
1. What specifically went wrong
2. Why
3. What the user should do to fix it (next steps - how to fix, or what to read)

Also logging AVX status (loaded binaries and CPU support) on ND4J initialization would be a good improvement.

**Comment by raver119** [comment]
Couple of weeks before release @saudet added cpuinfo to jcpp presets for this purpose. It's time to finally adopt it :)

**Comment by saudet** [comment]
The reason we haven't been adding the AVX2 and AVX512 binaries to nd4j-native-platform by default is because they crash if we try to load them on machines that don't support these instructions. The idea would be add everything to nd4j-native-platform, check what's available with [cpu_features](https://github.com/bytedeco/javacpp-presets/tree/master/cpu_features), and remove from JavaCPP's load list anything that we can't use, before attempting to load anything. That should happen in a LoadEnabled.init() method implemented by Nd4jCpuPresets. That's also where we could log whatever we want about that.

**Comment by AlexDBlack** [comment]
> The idea would be add everything to nd4j-native-platform, check what's available with cpu_features, and remove from JavaCPP's load list anything that we can't use

Hm, yes, that's a much better solution.

So then it's just AVX logging and usability when only binaries present are those for other OSs only...

**Comment by raver119** [comment]
What will be final binary size in this case? Around 150-200MB i suppose?

**Comment by raver119** [comment]
Implemented and merged: now we check for both min and max possible instruction sets, and validate stuff.
