### ISSUE TITLE
Not supported by Android below api 26

### ISSUE THREAD

**Issue by forever1078** [eclipse/deeplearning4j#7906]
```
val trainData = File(rootDir + "mnist_png/training")
val trainSplit = FileSplit(trainData, NativeImageLoader.ALLOWED_FORMATS, Random(1234))
val labelMaker = ParentPathLabelGenerator()
```
I tried to train mnist dataset on android and I found that it doesn't work below api 26 when I use FileSplit function, the error is

`java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)`

How to do below android api 26?

**Comment by AlexDBlack** [comment]
You must be on an old version. DataVec doesn't use the File.toPath() anywhere anymore (that I can see).

In fact we barely use this method anywhere outside of testing at all:
https://github.com/eclipse/deeplearning4j/search?q=toPath&unscoped_q=toPath

A number of releases ago this was in fact used in DataVec, but that has since been fixed.
Upgrade to 1.0.0-beta4 and try again. If this still occurs on beta4, please provide the full stack trace and we can re-open this.
