### ISSUE TITLE
dl4j beta4 F1 score 0 Vs beta3 F1 score 0.99

### ISSUE THREAD

**Issue by localmaxima** [eclipse/deeplearning4j#8191]
I trained a CNN model that learnt to do predictions with 99% Accuracy, F1Score, precision and recall. That was with dl4j 1.0.0-beta3

Moving to beta4, the model Accuracy is ok but the F1 Score, precision and recall are all zero or nan.

For sure there is something wrong but I can't find out what is it.
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta4
* Platform information (OS, etc): Ubuntu 16.04
* CUDA version, if used : 9.2
* NVIDIA driver version, if in use: Latest
* docker version: 19.03.1
*Nvidia docker: version 2
I use docker swarm to manage the cluster. Swarm manager will run spark master and swarm nodes will be the workers.

To start the swarm manager
`sudo docker swarm init --advertise-addr <sparkMasterHostName>`

This will output a token, to be used by workers to joint the swarm
`sudo docker swarm join --token <token> <sparkMasterHostName>:2377`

I created two branches. One branch runs beta3 and the other runs beta4. The issue can't be reproduced using a parallelwrapper. It must run on a cluster to reproduce.

I used a cluster on Azure, a master with two slaves, all running docker engine. All  images used are available publicly and the dataset resides in Azure open container, no password or key required. Each machine has 4 GPUS (Nvidia p40)

To run it, all you have to do is run docker stack deploy from the root folder:
`docker stack deploy --compose-file docker-compose.yml dl4j_min_example`

The output will be in the logs of the spark-submit container in the master node, to view it, just use  `Docker logs -f <spark-submit-container-id>`

Attached are the links to the two branches as well as gist files for the output of the two runs.
beta4 branch: https://github.com/localmaxima/dl4j-azure-minimal-example/tree/feature/1.0.0-beta4-F1_0-azure
beta4 output: https://gist.github.com/localmaxima/de9aec7d15db4c81316532efdb408ceb

beta3 branch: https://github.com/localmaxima/dl4j-azure-minimal-example/tree/feature/1.0.0-beta3-F1_99-azure
beta3 output: https://gist.github.com/localmaxima/9b09b3dddd6aae1b24b2562709be0d09

**Comment by aelkayesh** [comment]
Given the amount of time spent to create such a ticket with all required setup(Docker/Spark...etc),  and given that it's been six months without even a comment or any reaction on my ticket, I will just close it and thank you guys for your past efforts.

**Comment by agibsonccc** [comment]
@localmaxima  I'll admit we dropped the ball here and apologize for that. If you have any support issues like this in the future, please move all support to https://community.konduit.ai/ where we have a dedicated support team now. Sorry but Q4 was a brutal quarter for us and some things slipped. Part of that was our support. We were in the midst of a  big migration at that time. Hate to tell you, but frankly till recently we were under resourced we're just now getting proper hires in place for a lot of things. Remember, we're people to and have to pay the bills ourselves. Because we're people we also make mistakes. Please make sure to bump issues next time, as I mentioned sometimes things get missed because of backlog.

Some feedback on  ticket, honestly reading it for the first time, my first reaction is: where's the model? We have tuning advice right in the docs that should have helped you. The different versions of dl4j don't feel like they would have been the problem here. It feels like a fairly normal tuning issue. Just of note here is parameter averaging in general does have a few consequences on the training and I advise using ParallelWrapper (which does parameter averaging and imitates our spark implementation) to test the network's initial training first.
