### ISSUE TITLE
UnsupportedKerasConfigurationException: No SameDiff Lambda layer found for Lambda layer ctc. 

### ISSUE THREAD

**Issue by ziyuwzf** [eclipse/deeplearning4j#8192]
#### Issue Description

when i import keras model ,it shows that
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: No SameDiff Lambda layer found for Lambda layer ctc. You can register a SameDiff Lambda layer using KerasLayer.registerLambdaLayer(lambdaLayerName, sameDiffLambdaLayer);. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 1.0.0beta4
* no CUDA

**Comment by rnett** [comment]
Take a look at https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/e2e/KerasLambdaTest.java

There's basically no documentation on it, but that example should be what you need.

**Comment by ziyuwzf** [comment]
i follow your suggestion,but when i "import org.nd4j.resources.Resources;",it shows that "can not resolve resources",how can i import org.nd4j.resources.Resources?and where is the jar file that builded  deeplearning4J?

**Comment by rnett** [comment]
Its for accessing test resources, you shouldn't need to use it.  It lets the test access files from the `dl4j-test-resources` project, which is where we store model files and stuff for tests, that don't need to go into production.

You should be able to use whatever existing code you have for accessing the model file and doing the import, just add on the `KerasLayer.registerLambdaLayer` and the `SameDiffLambda` classes and instances.

**Comment by fxbronk** [comment]
Hello everyone, I am trying to import my Python Tensorflow Keras model to a `ComputationGraph`  using `importKerasModelAndWeights` and get the same error as described by @ziyuwzf. I was following the provided example but can't seem to figure out a solution for my specific case.

Within the Tensorflow Keras model I use a lambda layer to squeeze a tensor:
`x_cnn = tf.keras.layers.Lambda(lambda x: tf.keras.backend.squeeze(x, 1))(x_cnn)`

`squeeze` of `org.nd4j.linalg.factory.Nd4j` returns an `INDArray` so that I am somewhat lost. After all `defineLayer` returns a `SDVariable`. Can you guys give me a hint how to get the squeezing layer to work in the `ComputationGraph`?

Any help is highly appreciated

**Comment by AlexDBlack** [comment]
@fxbronk There's 2 APIs to be aware of here:
* ND4J, which is like numpy (i.e., INDArray)
* SameDiff, which is like tensorflow

you need to use SameDiff API not ND4J. In summary, the defineLayer(SameDiff sd, SDVariable x) method should for your lambda layer should look like:
```
 public SDVariable defineLayer(SameDiff sd, SDVariable x) {
    return sd.squeeze(x, 1);
}
```

**Comment by fxbronk** [comment]
Hello @AlexDBlack, thank you, you made my day! Works like a charm.
I was not yet familiar enough with dl4j to figure the difference between ND4J and SameDiff. Anyways, problem solved :).
