### ISSUE TITLE
IRIS Flower Example

### ISSUE THREAD

**Issue by FlameN** [eclipse/deeplearning4j#87]
Hello, I tried to run IrisExample, and got pretty poor results. If i enable asserts (-ea), i see an assert during finetune step. (W contains NaN)

I tried to use Iris Flower tutorial code, and got the same obstacle.

I used release 0.0.3.2.
Where is my fault?

**Comment by jureks** [comment]
I have the same problem on Windows. I downloaded the set of jars recommended at http://deeplearning4j.org/download.html, version 0.0.3.2.5 based on Jblas, so all components should be consistent. Using Iris example my F1 is about 0.5 and it varies slightly from ran to run. Moreover, the net seems to be insensitive to any changes in configuration, so I suppose the reason is a technical problem. How can I cure it?
