### ISSUE TITLE
Scala Examples

### ISSUE THREAD

**Issue by josemarialuna** [eclipse/deeplearning4j#965]
Do you have Deeplearning4j Spark Examples Repo in Scala? I have seen that you have it in Java.
Have you planned doing it soon?

Thank you!

**Comment by agibsonccc** [comment]
We have some now..not a ton. @romeokienzler could probably add more on request though

**Comment by romeokienzler** [comment]
Ok, will create a pull request soon, currently struggling to use the maven scala plugin properly https://github.com/romeokienzler/dl4j-examples/tree/master/dl4j-examples-scala

**Comment by huitseeker** [comment]
Anything I can help you with to make sure your contrib gets in @romeokienzler ?

**Comment by romeokienzler** [comment]
@huitseeker Dear Francois, thanks for offering help. Currently the task it to merge the following [pom.xml](https://github.com/romeokienzler/dl4j-examples/blob/master/dl4j-examples-scala/pom.xml) into [this one](https://github.com/deeplearning4j/dl4j-examples/blob/master/pom.xml). I've done some efforts but it clearly didn't work out for Eclipse and the Maven plugin. So either we merge or we create two separate project, one for Java and one for Scala...I can volunteer to maintain the Scala one then...

**Comment by huitseeker** [comment]
- we have a Scala module in dl4j, where the scala-maven plugin is set up in the parent pom:
https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-scaleout/spark/dl4j-spark-ml
- have you considered creating a child module of the dl4j-examples project that would contain your scala examples?
- can you point me to your attempt at a merge and show me what error, if any, you encounter? It's unclear what your issue is.
- Why would we need separate Java / Scala projects? While a vanilla java pom has trouble dealing with scala, a scala pom equipped with the scala-maven plugin usually deals with Java sources without issue.
- I'd like to see if we can have a pom that works on the ocmmand line, irrespectively of the editor, as a first step. Then we can add compatibility with Eclipse. I'm confident this is possible : Scala-IDE itself is a mixed Java / Scala project built with maven.
- you seem to be using the shade plugin for shipping an uber-jar for spark, is that correct? it seems there would be no problem doing that in your own module.

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
